// Auto-generated by @choiceform/icons-sprite
// Do not edit this file manually

export type IconName = 'icon-add-tiny' | 'icon-menu' | 'icon-search' | 'icon-settings' | 'icon-trash'

export interface IconMap {
  'icon-add-tiny': string
  'icon-menu': string
  'icon-search': string
  'icon-settings': string
  'icon-trash': string
}

export const iconNames = [
  "icon-add-tiny",
  "icon-menu",
  "icon-search",
  "icon-settings",
  "icon-trash"
] as const
